### PR TITLE
New implementation

### LINKED ISSUE #72: Make datepicker customizable
Hi,

Datepicker is complicated ui element because everybody wants to render it differently. You just have to look at all the implementations available. For me none fits, I would need a mix of different approach. We could just take your issue #52 about year control, some does not need it, some wants double arrow and I'm more for a dropdown menu.

With angular 2 and ng-content I think we should be able to create a component flexible enough to cover all needs. I'm thinking about a `DatePickerCore` with a good API to be manipulated, a minimal static template and using multiple `<ng-content>` for the rest of the template. Then we could create some of the most common datepicker on top of that core (`DatePickerMinimal`, `DatePickerFull`) and for *uncommon* users like me, they could still create their own component based on `DatePickerCore`.

I could start working on yet another datepicker plugin but, if you are up to it, I would rather rally with you so we could build a good and flexible datepicker plugin for once.

### PR DESCRIPTION
**Pull request by ghetolay**
This closes #72.

I edited this post to remove all the explanation stuff. You can now find it on the [readme](https://github.com/jkuri/ng2-datepicker/tree/flex) directly.

The readme is too big, we will later keep the usage part and use docs/wiki for the rest.

So I see this PR as the base discussion about design matter around the new implementation. Then I'll open different issues per design choice to avoid mixing different subject and having a discussion too long.
## 

That's it ! The first alpha release is ready !!

### CODE REVIEW

**Comment by gelliott181** [comment]
Just wanted to drop a quick note: The style sheets are filled with duplicate styles, including some duplicates in the same block! I ran them through CSS Purge and didn't have any issues with display, so it might be worth it to run the stylesheet through it for the next update.

**Comment by ghetolay** [comment]
@gelliott181 I've converted the .css file into .scss and removed duplicate styles.

**Comment by ghetolay** [comment]
@jkuri Can you publish the flex branch into npm as a prerelease with a tag like `2.0.0-alpha1` ?
Also could you create the github pages for the repo so I can push the live demo ?

**Comment by jkuri** [comment]
@ghetolay hey, thanks for this. yes, I will do that.

**Comment by jkuri** [comment]
@ghetolay;
```sh
Error: Cannot find module './scripts/inline-resources'
```
did you forgot to publish?

**Comment by ghetolay** [comment]
@jkuri Yep `.gitignore` was hiding it from commit.
Should be good now.

**Pull request closed without merging**
