### PR TITLE
Added moduleId to the datepicker component

### PR DESCRIPTION
**Pull request by edimitchel**
WIthout moduleId, template would not be loaded correctly..

Please, take this PR and release a new version quickly.

A part of this, thanks you a lot for this component !

### CODE REVIEW

**Comment by jkuri** [comment]
Hi @edimitchel, its working fine for me without moduleId. How do you mean template would not be loaded?

**Comment by edimitchel** [comment]
I got an issue without this. It was thrown when I use the date picker in my project using SystemJS.
I just see a fork of your repo that modification was made: https://github.com/NightImmunity/ng2-datepicker/blob/master/src/components/ng2-datepicker.ts#L24

**Comment by jkuri** [comment]
okay, lets get this in then.

**Comment by edimitchel** [comment]
Can you publish the new version on NPM ?

**Comment by jkuri** [comment]
I am sorry but it doesn't get compiled in my case. I guess I'll need to revert it.

**Comment by edimitchel** [comment]
Hum.. I think you miss this in tsconfig.json:

```
{
    ...
    "module": "commonjs",
    ...
}
```

**Comment by jkuri** [comment]
I guess so, since nobody was complaining about this issue so far I think it's not necessary.

**Comment by jkuri** [comment]
I think the best option for SystemJS would be to build own version with sytemjs-builder.

**Comment by edimitchel** [comment]
I not agree with you..
In the same fork repo, I found that module attribute is added in tsconfig: 

https://github.com/NightImmunity/ng2-datepicker/blob/master/tsconfig.json#L8

**Comment by jkuri** [comment]
can you try installing package with `npm install NightImmunity/ng2-datepicker --save` please?

**Comment by edimitchel** [comment]
I can but this fork was very different of your repo.. The owner of the fork adds bootstrap that I doesn't want..

**Comment by jkuri** [comment]
I am not really sure, but I have `commonjs` setted in my `tsconfig.json`. VSCode does underline `moduleId: module.id` even before I try to compile. Maybe its the `tslint.json`, are you sure this is still valid?

**Comment by edimitchel** [comment]
My friend, next, my tsconfig.json : (note the exclude attribute)

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "noEmitOnError": false,
    "removeComments": true,
    "target": "es5"
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ]
}
```

**Comment by jkuri** [comment]
okay, can you please provide another PR with this configuration included? I will accept it and make a publish to npm right away.

**Pull request merged**
